config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :articles do
    resources :comments
  end
  resources :users

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy", as: "logout"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    has_rich_text :body

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }

    include Visible
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end
  
  class_methods do
    def public_count
        where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/permission.rb
class Permission < Struct.new(:user)
  def allow?(controller, action)
    return true if controller == "welcome" #allow guests to show the landing page
    return true if controller == "sessions" #allow login actions for guests
    #return true if controller == "users" && action.in?(%w[new create])
    return true if controller == "articles" && action.in?(%w[index show])
    return true if controller == "comments" && action != "destroy"
    if user
      #return true if controller == "users" && action.in?(%w[edit update])
      return true if user.admin?
    end
    false
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    validates :email, presence: true, uniqueness: true
    validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorize

    delegate :allow?, to: :current_permission
    helper_method :allow?

    private

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :current_user

    def current_permission
        @current_permission ||= Permission.new(current_user)
    end

    def authorize
        if !current_permission.allow?(params[:controller], params[:action])
            flash[:danger] = "Action is not authorized."
            redirect_to root_url
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:success] = 'Article created !'
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      flash[:success] = "Article updated !"
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:info] = "Article deleted"

    redirect_to articles_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  invisible_captcha only: [:create]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    flash[:success] = "Commented !"
    
    redirect_to article_path(@article)
  end

  def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      flash[:info] = "Article deleted"

      redirect_to article_path(@article), status: 303
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in !"
      redirect_to root_path
    else
      flash.now[:danger] = "Email or password is incorrect"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:info] = "Disconnected"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            session[:user_id] = @user.id
            flash[:success] = "Account created !"
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :username, :password, :password_confirmation, :admin)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <%= form.label :body %><br>
    <%= form.rich_text_area :body %><br>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles 📔</h1>

<p> This blog has a whopping <%= Article.public_count %> articles and counting ! <br>
It also happens to have <%= pluralize Comment.count, "supportive comment" %>, how wholesome !</p>

<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>
</ul>

<% if allow?("articles", "create") %>
  <%= link_to "New Article", new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<div class="right-align">
  <%= link_to "Go back", articles_path %>
  <% if allow?("articles", "edit") %>
    <%= link_to "Edit", edit_article_path(@article) %>
  <% end %>
  <% if allow?("articles", "destroy") %>
    <%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
  <% end %>
</div>

<h3>Comments</h3>
<% @article.comments.each do |comment| %>
  <%= render comment %>
<% end %>

<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<div class="comment-box">
  <p>
    <span class="fa-solid fa-user" title="Commented by"> :</span>
    <%= comment.commenter %>
  </p>
  <blockquote>
    <%= comment.body %>
  </blockquote>
  <p class="right-align">
    <% if allow?("comments", "destroy") %>
      <%= link_to "Destroy Comment", [comment.article, comment], data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
    <% end %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <fieldset>
    <legend>Add a comment</legend>
    <div>
      <span class="fa-solid fa-user"> </span>
      <%= form.label :commenter, "Name" %><br>
      <%= form.text_field :commenter %>
    </div>
    <div>
      <span class="fa-regular fa-comment"> </span>
      <%= form.label :body, "Message" %><br>
      <%= form.text_area :body %>
    </div>
    <%= invisible_captcha %>
    <div>
      <%= form.submit %>
    </div>
  </fieldset>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apollow's corner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/e5ed7da8f9.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <nav>
          <%= link_to "Home", root_path %>
          <%= link_to "Articles", articles_path %>

          <% if current_user %>
            [<%= current_user.username %>]
            <%= link_to "Log out", logout_path %>
          <% else %>
            <%= link_to "Login", login_path %>
          <% end %>
      </nav>
      <h1>idkwhyimstillalive</h1>
    </header>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"
           data-controller="removals"
           data-action="animationend->removals#remove"
      >
        <%= value %>
      </div>
    <% end %>
    <% flash.clear%>


    <%= yield %>
  </body>

  <footer>
    <%= link_to "Home", root_path %>
  </footer>
</html>

app/views/users/_form.html.erb
<%= form_with model: user do |f|  %>
    <p>
    <% user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
    </p>
    <p>
    <% user.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
    </p>
    <p>
    <% user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
    </p>
    <p>
    <% user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
    </p>
    <p>
    <%= f.submit "Sign Up" %>
    </p>
<% end %>

app/views/users/new.html.erb
<h1>Create a new account</h1>

<%= render "form", user: @user %>

app/views/welcome/index.html.erb
<h2>My precious little corner ?</h2>

<p>This is simply the landing page of a website that I built
to output what goes through my mind whenever I'm down in the 
deepest pits of hell.</p>

<p>You can follow me <%= link_to "here", articles_path %> to list all my wonderful articles </p>

<h2>Filler</h2>

<p>Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead. Cum horribilem walking dead resurgere de crazed sepulcris creaturis, zombie sicut de grave feeding iride et serpens. Pestilentia, shaun ofthe dead scythe animated corpses ipsa screams. Pestilentia est plague.</p>